name: Bug Report
description: Report a bug in the Ahrefs Python SDK
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      render: python
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SDK version
      description: Output of `pip show ahrefs-python` or your pinned version.
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Output of `python --version`.
    validations:
      required: true
